apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  labels:
    app: elasticsearch
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0  
          ports:
            - containerPort: 9200  
            - containerPort: 9300  
          env:
            - name: discovery.type
              value: single-node  
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m" 
            - name: xpack.security.enabled
              value: "false" 
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data 
      volumes:
        - name: es-data
          emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: transport
      port: 9300
      targetPort: 9300
      protocol: TCP
  type: ClusterIP 
